name: Docker

on:
  schedule:
    - cron: '15 0 * * 5'
  push:
    branches: ["mautic4"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  branch: mautic4
  platforms_to_build_for: linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
        with:
          target_sync_branch: ${{ env.branch }}
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: ${{ env.branch }}
          upstream_sync_repo: mautic/docker-mautic
          upstream_repo_access_token: ${{ secrets.UPSTREAM_REPO_SECRET }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apache/Dockerfile
          platforms: ${{ env.platforms_to_build_for }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ github.ref }}:latest